name: terraform

on:
  pull_request:
    branches: ["main"] # PR contra main → plan prod
  push:
    branches:
      - "main"               # merge a main → plan + apply prod
      - "dev/**"             # push a ramas dev/** → plan + apply test
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  TF_VERSION: "1.6.6"
  TF_LOG: "INFO"
  TF_LOG_PATH: "terraform.log"

jobs:
  plan:
    runs-on: ubuntu-latest

    environment: ${{ github.ref_name == 'main' && '' || 'test' }}

    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Select env name
        id: env
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" || "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "env=prod" >> $GITHUB_OUTPUT
            echo "TF_LOG=INFO" >> $GITHUB_ENV
          else
            echo "env=test" >> $GITHUB_OUTPUT
            echo "TF_LOG=DEBUG" >> $GITHUB_ENV
          fi

      - name: Debug OIDC token
        run: |
            echo "Dumping OIDC token claims..."
            TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" \
            -H "Authorization: Bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" | jq -r '.value')
            echo "$TOKEN" | cut -d '.' -f2 | base64 -d | jq .

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -backend-config=../backends/${{ steps.env.outputs.env }}.hcl

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -var-file=../environments/${{ steps.env.outputs.env }}.tfvars -out=tfplan

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ steps.env.outputs.env }}
          path: terraform/tfplan

      - name: Upload debug logs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-logs-${{ steps.env.outputs.env }}
          path: terraform/terraform.log

  apply:
    needs: plan
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    environment: ${{ github.ref_name == 'main' && 'prod' || 'test' }}

    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Select env name
        id: env
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "env=prod" >> $GITHUB_OUTPUT
            echo "TF_LOG=INFO" >> $GITHUB_ENV
          else
            echo "env=test" >> $GITHUB_OUTPUT
            echo "TF_LOG=DEBUG" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform init
        run: terraform init -backend-config=../backends/${{ steps.env.outputs.env }}.hcl

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ steps.env.outputs.env }}
          path: terraform

      - name: Terraform apply (exact plan)
        run: terraform apply -lock-timeout=300s -auto-approve tfplan

      - name: Terraform output
        run: |
          echo "Region: ${{ vars.AWS_REGION }}"
          echo "ECR Name: $(terraform output -raw ecr_name)"
          echo "ECR Repo URL: $(terraform output -raw ecr_repository_url)"
          echo "EKS Cluster Name: $(terraform output -raw eks_name)"
          echo "EKS Cluster Endpoint: $(terraform output -raw eks_endpoint)"
          echo "EKS OIDC Issuer: $(terraform output -raw eks_oidc_issuer)"

      - name: Upload apply debug logs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-apply-logs-${{ steps.env.outputs.env }}
          path: terraform/terraform.log

  graph:
    needs: plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Select env name
        id: env
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "env=prod" >> $GITHUB_OUTPUT
          else
            echo "env=test" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Terraform init
        run: terraform init -backend-config=../backends/${{ steps.env.outputs.env }}.hcl

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ steps.env.outputs.env }}
          path: terraform

      - name: Generate graph PNG
        run: terraform graph -type=plan terraform/tfplan | dot -Tpng > terraform-graph.png

      - name: Upload graph artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-graph-${{ steps.env.outputs.env }}
          path: terraform/terraform-graph.png
